# Generated by Django 3.2.8 on 2021-12-16 09:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ContactRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactregister',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
