# Generated by Django 3.2.8 on 2022-04-22 06:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ContactRegister', '0002_alter_contactregister_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactregister',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contactregister',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
