# Generated by Django 3.2.8 on 2022-04-26 05:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ContactRegister', '0003_auto_20220422_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactregister',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
